### ISSUE TITLE
center product logos within white box

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/apps-gov#49] opened 2016-03-10 01:59 UTC
- [x] home page
- [x] products page
- [x] individual products

**Comment by lukad03** [comment] 2016-03-10 18:10
Closing - images aren't centered vertically on products by design, and individual products are already centered within their bounding box. Homepage product images have been centered-ish. Not sure how to take this further in the confines of CSS

**Closed as completed** 2016-03-10 18:09 UTC

**Comment by stroupaloop** [comment] 2016-03-10 18:11
got it, thanks!

On Thu, Mar 10, 2016 at 1:10 PM, Luke Keller notifications@github.com
wrote:

> Closing - images aren't centered vertically on products by design, and
> individual products are already centered within their bounding box.
> Homepage product images have been centered-ish. Not sure how to take this
> further in the confines of CSS
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/apps-gov/issues/49#issuecomment-194982072
> .

## 

Andrew Stroup | presidential innovation fellows
director of product and technology
e: andrew.stroup@pif.gov
https://presidentialinnovationfellows.gov
